language: java
before_script:
- git config --global user.email "monaka@monami-ya.jp"
- git config --global user.name "Masaki Muranaka"
- git config credential.helper "store --file=.git/credentials"
- git clone https://${GH_TOKEN}@github.com/PizzaFactory/mRDT.git p2repo
- echo "https://${GH_TOKEN}@github.com" > p2repo/.git/credentials
- (cd p2repo && git checkout gh-pages)
script: mvn -f parent/pom.xml deploy
after_success:
- cp -r p2update/target/repository/ p2repo/${PIZZAFACTORY_VERSION}/travis-build-${TRAVIS_BUILD_NUMBER}/
- (cd p2repo && ruby ./generate_update.rb && git add . && git commit -m 'Added by Travis-CI builder.' && git push)
env:
  global:
  - MAVEN_OPTS=-Xmx1024m
  - PIZZAFACTORY_VERSION=8.5
  - GIT_COMMITTER_NAME="Masaki Muranaka"
  - GIT_COMMITTER_EMAIL="monaka@monami-ya.jp"
  - secure: G7GSae9EJHdmmF1Nbv25vRuX9bKyedlVd7C6spIOJ/rX0AOoTRhZpWIrp8gvEdDc9Mock2djfpHsWwUYCkpW1yorao8MSY2u9SX5lu9vF0ACPdsqiRamvHEkVeu/nipf1fNBGkB5d2Ejdt4vMBUIuadK2c3PEbZqQULbRwgAG/k=
