language: java
jdk:
- oraclejdk8
sudo: false
script: mvn -f parent/pom.xml deploy
after_success:
- git clone --depth=1 -b gh-pages https://${GH_TOKEN}@github.com/PizzaFactory/mRDT.git gh-pages
- cd gh-pages
- mvn process-resources install
env:
  global:
  - PIZZAFACTORY_VERSION=8.5
  - GIT_COMMITTER_NAME="Masaki Muranaka"
  - GIT_COMMITTER_EMAIL="monaka@monami-ya.jp"
  - secure: "GgAuBEqtP5Uqw4sH01kAVekFbSYk44BjI2FI/TS2yreqbc2jPU2cj7Yxu+B+4CGN+4n2MgObBoTejY6wOpzTVbVmewdhJMbAM6bThm2XtLIlPkonFq8US9UCkqEiPcNyFIHVFQPqDPhH1lEqX9m+3T0cMA1qxF2hY4VmnbjA1uc="
